library(readr)
myData <- read_delim("data/household_power_consumption.txt", delim = ";", col_names = T)
par(mfrow = c(1,3), mar = c(5,4,2,1))
hist(myData$Sub_metering_1, col = "green", xlab = "SubMetering 1")
hist(myData$Sub_metering_2, col = "blue", xlab = "SubMetering 2")
hist(myData$Sub_metering_3, col = "red", xlab = "SubMetering 3")